FROM maven:3.6-jdk-13 AS build
MAINTAINER maximilian schiedermeier
COPY LobbyService/src /usr/src/app/src
COPY LobbyService/pom.xml /usr/src/app
RUN mvn -f /usr/src/app/pom.xml clean package -P prod

## Discard Maven, run JAR file using JRE
FROM openjdk:8-jre-alpine

## Wait for SQL to be ready
ENV WAIT_VERSION 2.7.2
ADD https://github.com/ufoscout/docker-compose-wait/releases/download/$WAIT_VERSION/wait /wait
RUN chmod +x /wait

# copy the jar from the build stage, expose the required port and run it.
COPY --from=build /usr/src/app/target/ls.jar /usr/app/ls.jar
EXPOSE 4242

# allow debug if startup fails, with: docker run -it --entrypoint /bin/bash ls-api -s
RUN apk add --no-cache bash coreutils grep sed
